#ifndef __INC_METIN_II_LENGTH_H__
#define __INC_METIN_II_LENGTH_H__

#include "CommonDefines.h"

#define WORD_MAX 0xffff
enum EMisc
{
	CHANNEL_99				= 99,

	MAX_HOST_LENGTH			= 15,
	IP_ADDRESS_LENGTH		= 15,
	LOGIN_MAX_LEN			= 30,
	PASSWD_MAX_LEN			= 16,
#ifdef ENABLE_HWID_BAN
	HWID_MAX_LEN			= 64,
#endif
#ifdef ENABLE_PLAYER_PER_ACCOUNT5
	PLAYER_PER_ACCOUNT		= 5,
#else
	PLAYER_PER_ACCOUNT		= 4,
#endif
	ACCOUNT_STATUS_MAX_LEN	= 8,
	CHARACTER_NAME_MAX_LEN	= 48,	//@fixme412	Original: 24
	SHOP_SIGN_MAX_LEN		= 32,
	CHARACTER_FOLDER_MAX_LEN = 64,

	//INVENTORY_WINDOW
	INVENTORY_PAGE_COLUMN	= 5, // 5 (default)
	INVENTORY_PAGE_ROW		= 9, // 9 (default)
	INVENTORY_PAGE_SIZE		= INVENTORY_PAGE_COLUMN*INVENTORY_PAGE_ROW,
#if defined(ENABLE_EXTEND_INVEN_SYSTEM) || defined(ENABLE_EXTEND_INVEN_PAGE_SYSTEM)
	INVENTORY_PAGE_COUNT	= 4, // 2 (default)
#else
	INVENTORY_PAGE_COUNT	= 2, // 2 (default)
#endif
	INVENTORY_MAX_NUM		= INVENTORY_PAGE_SIZE*INVENTORY_PAGE_COUNT, // 90 (default)
	//END_INVENTORY_WINDOW

	ABILITY_MAX_NUM			= 50,
	EMPIRE_MAX_NUM			= 4,
	BANWORD_MAX_LEN			= 24,
	SMS_MAX_LEN				= 80,
	MOBILE_MAX_LEN			= 32,
	SOCIAL_ID_MAX_LEN		= 18,
	GUILD_NAME_MAX_LEN		= 12,
#ifdef ENABLE_EVENT_MANAGER
	QUEST_NAME_MAX_NUM		= 64,
#endif
#ifdef ENABLE_MYSHOP_DECO
	SHOP_HOST_ITEM_MAX		= 80,
#endif
	SHOP_HOST_ITEM_MAX_NUM	= 40,
	SHOP_GUEST_ITEM_MAX_NUM = 18,
	SHOP_PRICELIST_MAX_NUM	= 40,
#ifdef ENABLE_TICKET_SYSTEM
	CHAT_MAX_LEN			= 700,
#else
	CHAT_MAX_LEN			= 512,
#endif
	QUICKSLOT_MAX_NUM		= 36,
	QUICKSLOT_MAX_POS		= 255,	//ENABLE_BELT_INVENTORY
	JOURNAL_MAX_NUM			= 2,
	QUERY_MAX_LEN			= 8192,
	FILE_MAX_LEN			= 128,
	PLAYER_EXP_TABLE_MAX	= 120,
	PLAYER_MAX_LEVEL_CONST	= 250,
#ifdef ENABLE_YOHARA_SYSTEM
	PLAYER_CONQUEROR_LEVEL	= 30,
#endif
#ifdef ENABLE_GROWTH_PET_SYSTEM
	GROWTHPET_MAX_LEVEL_CONST = 105,
	PET_NAME_MAX_SIZE		= 20,
	PET_REVIVE_MATERIAL_SLOT_MAX = 10,
#endif
#if defined(ENABLE_GUILDRENEWAL_SYSTEM) && defined(ENABLE_EXTENDED_GUILD_LEVEL)
	GUILD_MAX_LEVEL			= 40,
	MAX_GUILD_DONATION_PER_DAY = 3,
#else
	GUILD_MAX_LEVEL			= 20,
#endif
	MOB_MAX_LEVEL			= 100,
	ATTRIBUTE_MAX_VALUE		= 20,
	CHARACTER_PATH_MAX_NUM	= 64,
	SKILL_MAX_NUM			= 255,
	SKILLBOOK_DELAY_MIN		= 64800,
	SKILLBOOK_DELAY_MAX		= 108000,
	SKILL_MAX_LEVEL			= 40,
	REFINE_SKILL_MAX_LEVEL	= 20,
#ifdef ENABLE_INGAME_WIKI
	MAX_REFINE_COUNT		= 9,
#endif
	APPLY_NAME_MAX_LEN		= 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,
	MOB_SKILL_MAX_NUM		= 5,
#ifdef ENABLE_ATTR_6TH_7TH_EXTEND
	POINT_MAX_NUM			= 500,
#else
    POINT_MAX_NUM			= 255,
#endif
	//DRAGONSOUL_WINDOW
	DRAGON_SOUL_BOX_SIZE	= 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	//END_DRAGONSOUL_WINDOW

#ifdef ENABLE_ATTR_6TH_7TH
	c_SkillBook_Comb_Slot_Max = 10,
	GOLD_COMB_SKILLBOOK = 100000,
	NPC_STORAGE_SLOT_COUNT = 1,
	FRAGMENT_BOX_VNUM = 39067,
#endif
#ifdef ENABLE_SUMMER_EVENT_ROULETTE
	ROULETTE_ITEM_MAX = 20,
	SOUL_MAX = 999999,
	SOUL_RE_MAX = 999999,
#endif

	MAX_AMOUNT_OF_MALL_BONUS	= 20,
#if defined(ENABLE_PROTO_RENEWAL_CUSTOM) && defined(ENABLE_PET_SYSTEM)
	WEAR_MAX_NUM				= 33,
#else
	WEAR_MAX_NUM				= 32,
#endif

	//LIMIT_GOLD
	GOLD_MAX				= 2000000000,
#ifdef ENABLE_CHEQUE_SYSTEM
	CHEQUE_MAX				= 1000,
#ifdef ENABLE_CHEQUE_EXCHANGE_WINDOW
	TAX_MUL					= 3,
	CHEQUE_NAME_VALUE		= 100000000,
#endif
#endif
#ifdef ENABLE_BATTLE_FIELD
	BATTLE_POINT_MAX			= 2000000000,
	LIMIT_DAILY_MAX_BATTLE		= 1000,
#endif
#ifdef ENABLE_MEDAL_OF_HONOR
	MEDAL_OF_HONOR_MAX			= 2000000000,
	LIMIT_DAILY_MAX_MEDALS		= 1000,
#endif
	//END_LIMIT_GOLD

	OPENID_AUTHKEY_LEN		= 32,
	SHOP_TAB_NAME_MAX		= 32,
	SHOP_TAB_COUNT_MAX		= 3,	//@fixme537

	//BELT_WINDOW
#ifdef ENABLE_BELT_INVENTORY_RENEWAL
	BELT_INVENTORY_SLOT_WIDTH = 6,
	BELT_INVENTORY_SLOT_HEIGHT = 6,
#else
	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,
#endif
	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,
	//END_BELT_WINDOW

	//EXCHANGE_WINDOW
	EXCHANGE_PAGE_COLUMN	= 4,
	EXCHANGE_PAGE_ROW		= 3,
	EXCHANGE_PAGE_SIZE		= EXCHANGE_PAGE_COLUMN*EXCHANGE_PAGE_ROW,
	//END_EXCHANGE_WINDOW
};

#ifdef ENABLE_GEM_SYSTEM
enum EGemSystem
{
	GEM_REFRESH_ITEM_VNUM		= 39063,
	GEM_UNLOCK_ITEM_VNUM		= 39064,
	GEM_GLIMMERSTONE_VNUM		= 50926,
	GEM_REFRESH_PULSE			= 5 * 3600, //hours
	GEM_SHOP_HOST_ITEM_MAX_NUM	= 9,
	GEM_MAX						= 1000000,
};
#endif

#ifdef ENABLE_SWITCHBOT
enum SwitchbotValues
{
	SWITCHBOT_SLOT_COUNT = 7,
	SWITCHBOT_ALTERNATIVE_COUNT = 5,
	//1 = Switching Item
	//2 = Yang
	SWITCHBOT_PRICE_TYPE = 1,
	//Amount Swtichting Items the Yang-Price
	SWITCHBOT_PRICE_AMOUNT = 1,
};

const uint32_t c_arSwitchingItems[6] =
{
	70064,
	39028,
	71084,
	76014,
	71151,
	76023,
};
#endif

#ifdef ENABLE_REFINE_MSG_ADD
enum ERefineFailType
{
	REFINE_FAIL_GRADE_DOWN,
	REFINE_FAIL_DEL_ITEM,
	REFINE_FAIL_KEEP_GRADE,
	REFINE_FAIL_MAX,
};
#endif

enum EWearPositions
{
	WEAR_BODY,				// 0
	WEAR_HEAD,				// 1
	WEAR_FOOTS,				// 2
	WEAR_WRIST,				// 3
	WEAR_WEAPON,			// 4
	WEAR_NECK,				// 5
	WEAR_EAR,				// 6
	WEAR_SHIELD,			// 10
	WEAR_UNIQUE1,			// 7
	WEAR_UNIQUE2,			// 8
	WEAR_ARROW,				// 9
	WEAR_ABILITY1,			// 11
	WEAR_ABILITY2,			// 12
	WEAR_ABILITY3,			// 13
	WEAR_ABILITY4,			// 14
	WEAR_ABILITY5,			// 15
	WEAR_ABILITY6,			// 16
	WEAR_ABILITY7,			// 17
	WEAR_ABILITY8,			// 18
	WEAR_COSTUME_BODY,		// 19
	WEAR_COSTUME_HAIR,		// 20
	WEAR_COSTUME_MOUNT,		// 21	ENABLE_MOUNT_COSTUME_SYSTEM
	WEAR_COSTUME_ACCE,		// 22	ENABLE_ACCE_COSTUME_SYSTEM
	WEAR_COSTUME_WEAPON,	// 23	ENABLE_WEAPON_COSTUME_SYSTEM
	WEAR_COSTUME_AURA,		// 24	ENABLE_AURA_SYSTEM
	WEAR_RING1,				// 25
	WEAR_RING2,				// 26
	WEAR_BELT,				// 27
	WEAR_PENDANT,			// 28	ENABLE_PENDANT
#ifdef ENABLE_GLOVE_SYSTEM
	WEAR_GLOVE,				// 29
#endif
#ifdef ENABLE_PASSIVE_SYSTEM
	WEAR_PASSIVE_ATTR_UP,	// 30
	WEAR_PASSIVE_ATTR_DOWN,	// 31
#endif
#if defined(ENABLE_PROTO_RENEWAL_CUSTOM) && defined(ENABLE_PET_SYSTEM)
	WEAR_PET,
#endif

	WEAR_MAX = WEAR_MAX_NUM
};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,
	CATEGORY_MENTAL,
	CATEGORY_ATTRIBUTE,
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
#ifdef ENABLE_WOLFMAN_CHARACTER
	JOB_WOLFMAN,
#endif
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL	= (1 << 0),
	RACE_FLAG_UNDEAD	= (1 << 1),
	RACE_FLAG_DEVIL		= (1 << 2),
	RACE_FLAG_HUMAN		= (1 << 3),
	RACE_FLAG_ORC		= (1 << 4),
	RACE_FLAG_MILGYO	= (1 << 5),
	RACE_FLAG_INSECT	= (1 << 6),
	RACE_FLAG_DESERT	= (1 << 7),
	RACE_FLAG_TREE		= (1 << 8),
#ifdef ENABLE_PROTO_RENEWAL
	RACE_FLAG_DECO		= (1 << 9),
	RACE_FLAG_HIDE		= (1 << 10),
	RACE_FLAG_ATT_CZ	= (1 << 11),	//ENABLE_ELEMENT_ADD
	RACE_FLAG_AWEAKEN	= (1 << 12),
	RACE_FLAG_SUNGMAHEE	= (1 << 13),
	RACE_FLAG_OUTPOST	= (1 << 14),
	RACE_FLAG_UNKNOWN_1 = (1 << 15),
	RACE_FLAG_UNKNOWN_2	= (1 << 16),
#endif
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
#ifdef ENABLE_BELT_INVENTORY
	QUICKSLOT_TYPE_BELT = 16, // SLOT_TYPE_BELT_INVENTORY
#endif
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
	PART_ACCE,		//ENABLE_ACCE_COSTUME_SYSTEM
	PART_PENDANT,	//ENABLE_PENDANT
	PART_AURA,		//ENABLE_AURA_SYSTEM
	PART_MAX_NUM,
	PART_WEAPON_SUB,
};

enum EChatType : uint8_t
{
	CHAT_TYPE_TALKING,
	CHAT_TYPE_INFO,
	CHAT_TYPE_NOTICE,
	CHAT_TYPE_PARTY,
	CHAT_TYPE_GUILD,
	CHAT_TYPE_COMMAND,
	CHAT_TYPE_SHOUT,
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
#ifdef ENABLE_OX_RENEWAL
	CHAT_TYPE_CONTROL_NOTICE,
#endif
#ifdef ENABLE_DICE_SYSTEM
	CHAT_TYPE_DICE_INFO,
#endif
#ifdef ENABLE_12ZI
	CHAT_TYPE_MISSION,
	CHAT_TYPE_SUB_MISSION,
	CHAT_TYPE_CLEAR_MISSION,
#endif
#ifdef ENABLE_CHAT_SETTINGS
	CHAT_TYPE_EXP_INFO,
	CHAT_TYPE_ITEM_INFO,
	CHAT_TYPE_MONEY_INFO,
#endif

	CHAT_TYPE_MAX_NUM
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL			= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR			= 4,
	WHISPER_TYPE_GM				= 5,
	WHISPER_TYPE_SYSTEM			= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
#ifdef ENABLE_VIP_SYSTEM
	GM_VIP,
#endif
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR,
	GM_DISABLE,
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,		// 0
	CHAR_TYPE_NPC,			// 1
	CHAR_TYPE_STONE,		// 2
	CHAR_TYPE_WARP,			// 3
	CHAR_TYPE_DOOR,			// 4
	CHAR_TYPE_BUILDING,		// 5
	CHAR_TYPE_PC,			// 6
	CHAR_TYPE_POLYMORPH_PC,	// 7
	CHAR_TYPE_HORSE,		// 8
	CHAR_TYPE_GOTO,			// 9
#ifdef ENABLE_PROTO_RENEWAL
	CHAR_TYPE_PET,
	CHAR_TYPE_PET_PAY,
#endif
#ifdef ENABLE_PREMIUM_PRIVATE_SHOP
	CHAR_TYPE_SHOP,
#endif
	CHAR_TYPE_OBJECT, // used only for client-side
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,						// 0	- POINT_NONE,	0	Kein Bonus
	APPLY_MAX_HP,					// 1	- POINT_MAX_HP,	6	Max TP
	APPLY_MAX_SP,					// 2	- POINT_MAX_SP,	8	Max MP
	APPLY_CON,						// 3	- POINT_HT,	13	Vitalität
	APPLY_INT,						// 4	- POINT_IQ,	15	Intelligenz
	APPLY_STR,						// 5	- POINT_ST,	12		Stärke
	APPLY_DEX,						// 6	- POINT_DX,	14	Beweglichkeit
	APPLY_ATT_SPEED,				// 7	- POINT_ATT_SPEED,	17	Angriffsgeschwindigkeit
	APPLY_MOV_SPEED,				// 8	- POINT_MOV_SPEED,	19	Bewegungsgeschwindigkeit
	APPLY_CAST_SPEED,				// 9	- POINT_CASTING_SPEED,	21	Zaubergeschwindigkeit
	APPLY_HP_REGEN,					// 10	- POINT_HP_REGEN,	32	TP-Regeneration
	APPLY_SP_REGEN,					// 11	- POINT_SP_REGEN,	33	MP-Regeneration
	APPLY_POISON_PCT,				// 12	- POINT_POISON_PCT,	37	Vergiftungschance
	APPLY_STUN_PCT,					// 13	- POINT_STUN_PCT,	38	Ohnmachtchance
	APPLY_SLOW_PCT,					// 14	- POINT_SLOW_PCT,	39	Verlangsamungschance
	APPLY_CRITICAL_PCT,				// 15	- POINT_CRITICAL_PCT,	40	Kritische Treffer Chance
	APPLY_PENETRATE_PCT,			// 16	- POINT_PENETRATE_PCT,	41	Chance auf durchbohrenden Treffer
	APPLY_ATTBONUS_HUMAN,			// 17	- POINT_ATTBONUS_HUMAN,	43	Stark gegen Halbmenschen
	APPLY_ATTBONUS_ANIMAL,			// 18	- POINT_ATTBONUS_ANIMAL,	44	Stark gegen Tiere
	APPLY_ATTBONUS_ORC,				// 19	- POINT_ATTBONUS_ORC,	45	Stark gegen Orks
	APPLY_ATTBONUS_MILGYO,			// 20	- POINT_ATTBONUS_MILGYO,	46	Stark gegen Esoterische
	APPLY_ATTBONUS_UNDEAD,			// 21	- POINT_ATTBONUS_UNDEAD,	47	Stark gegen Untote
	APPLY_ATTBONUS_DEVIL,			// 22	- POINT_ATTBONUS_DEVIL,	48	Stark gegen Teufel
	APPLY_STEAL_HP,					// 23	- POINT_STEAL_HP,	63	Chance auf TP Raub
	APPLY_STEAL_SP,					// 24	- POINT_STEAL_SP,	64	Chance auf MP Raub
	APPLY_MANA_BURN_PCT,			// 25	- POINT_MANA_BURN_PCT,	65	Verbrennungschance
	APPLY_DAMAGE_SP_RECOVER,		// 26	- POINT_DAMAGE_SP_RECOVER,	66	Chance, MP bei Treffer zurückzuerhalten
	APPLY_BLOCK,					// 27	- POINT_BLOCK,	67	Chance auf Abblocken
	APPLY_DODGE,					// 28	- POINT_DODGE,	68	Chance auf Refkeltieren
	APPLY_RESIST_SWORD,				// 29	- POINT_RESIST_SWORD,	69	Schwertverteidigung
	APPLY_RESIST_TWOHAND,			// 30	- POINT_RESIST_TWOHAND,	70	Zweihandverteidigung
	APPLY_RESIST_DAGGER,			// 31	- POINT_RESIST_DAGGER,	71	Dolchverteidigung
	APPLY_RESIST_BELL,				// 32	- POINT_RESIST_BELL,	72	Glockenverteidigung
	APPLY_RESIST_FAN,				// 33	- POINT_RESIST_FAN,	73		Fächerverteidigung
	APPLY_RESIST_BOW,				// 34	- POINT_RESIST_BOW,	74	Pfeilwiderstand
	APPLY_RESIST_FIRE,				// 35	- POINT_RESIST_FIRE,	75	Feuerresistenz
	APPLY_RESIST_ELEC,				// 36	- POINT_RESIST_ELEC,	76	Blitzresistenz
	APPLY_RESIST_MAGIC,				// 37	- POINT_RESIST_MAGIC,	77	Magiewiderstand
	APPLY_RESIST_WIND,				// 38	- POINT_RESIST_WIND,	78		Windwiderstand
	APPLY_REFLECT_MELEE,			// 39	- POINT_REFLECT_MELEE,	79	Chance, Nahkampftreffer zu reflektieren
	APPLY_REFLECT_CURSE,			// 40	- POINT_REFLECT_CURSE,	80	Chance, Fluch zu reflektieren
	APPLY_POISON_REDUCE,			// 41	- POINT_POISON_REDUCE,	81	Giftwiederstand
	APPLY_KILL_SP_RECOVER,			// 42	- POINT_KILL_SP_RECOVER,	82	Chance MP Wiederherzustellen
	APPLY_EXP_DOUBLE_BONUS,			// 43	- POINT_EXP_DOUBLE_BONUS,	83	Chance auf EXP-Bonus
	APPLY_GOLD_DOUBLE_BONUS,		// 44	- POINT_GOLD_DOUBLE_BONUS,	84		Chance auf Yangbonus
	APPLY_ITEM_DROP_BONUS,			// 45	- POINT_ITEM_DROP_BONUS,	85	Chance mehr Gegenstände zu Droppen
	APPLY_POTION_BONUS,				// 46	- POINT_POTION_BONUS,	86	Trank % Effektzuwachs
	APPLY_KILL_HP_RECOVER,			// 47	- POINT_KILL_HP_RECOVERY,	87	Chance TP Wiederherzustellen
	APPLY_IMMUNE_STUN,				// 48	- POINT_IMMUNE_STUN,	88	Abwehr gegen Ohnmacht
	APPLY_IMMUNE_SLOW,				// 49	- POINT_IMMUNE_SLOW,	89	Abwehr gegen Verlangsamen
	APPLY_IMMUNE_FALL,				// 50	- POINT_IMMUNE_FALL,	90	Immun gegen Stürzen
	APPLY_SKILL,					// 51	- POINT_NONE
	APPLY_BOW_DISTANCE,				// 52	- POINT_BOW_DISTANCE,	34	Reichweite
	APPLY_ATT_GRADE_BONUS,			// 53	- POINT_ATT_GRADE_BONUS,	95		Angriffswert
	APPLY_DEF_GRADE_BONUS,			// 54	- POINT_DEF_GRADE_BONUS,	96	Verteidigung
	APPLY_MAGIC_ATT_GRADE,			// 55	- POINT_MAGIC_ATT_GRADE_BONUS,	97	Magischer Angriffswert
	APPLY_MAGIC_DEF_GRADE,			// 56	- POINT_MAGIC_DEF_GRADE_BONUS,	98	Magische Verteidigung
	APPLY_CURSE_PCT,				// 57	- POINT_CURSE_PCT,	42	Chance jemanden zu Verfluchen
	APPLY_MAX_STAMINA,				// 58	- POINT_MAX_STAMINA,	10	Max Ausdauer
	APPLY_ATTBONUS_WARRIOR,			// 59	- POINT_ATTBONUS_WARRIOR,	54	Stark gegen Krieger
	APPLY_ATTBONUS_ASSASSIN,		// 60	- POINT_ATTBONUS_ASSASSIN,	55	Stark gegen Ninja
	APPLY_ATTBONUS_SURA,			// 61	- POINT_ATTBONUS_SURA,	56	Stark gegen Sura
	APPLY_ATTBONUS_SHAMAN,			// 62	- POINT_ATTBONUS_SHAMAN,	57	Stark gegen Schamanen
	APPLY_ATTBONUS_MONSTER,			// 63	- POINT_ATTBONUS_MONSTER,	53	Stark gegen Monster
	APPLY_MALL_ATTBONUS,			// 64	- POINT_ATT_BONUS,	93	Angriffswert
	APPLY_MALL_DEFBONUS,			// 65	- POINT_MALL_DEFBONUS,	115	Verteidigung
	APPLY_MALL_EXPBONUS,			// 66	- POINT_MALL_EXPBONUS,	116	EXP
	APPLY_MALL_ITEMBONUS,			// 67	- POINT_MALL_ITEMBONUS,	117	Dropchance von Gegenständen
	APPLY_MALL_GOLDBONUS,			// 68	- POINT_MALL_GOLDBONUS,	118	Dropchance Yang
	APPLY_MAX_HP_PCT,				// 69	- POINT_MAX_HP_PCT,	119	Max. TP
	APPLY_MAX_SP_PCT,				// 70	- POINT_MAX_SP_PCT,	120	Max. MP
	APPLY_SKILL_DAMAGE_BONUS,		// 71	- POINT_SKILL_DAMAGE_BONUS,	121	Fertigkeitsschaden (FKS)
	APPLY_NORMAL_HIT_DAMAGE_BONUS,	// 72	- POINT_NORMAL_HIT_DAMAGE_BONUS,	122	Durchschnittlicher Schaden (DSS)
	APPLY_SKILL_DEFEND_BONUS,		// 73	- POINT_SKILL_DEFEND_BONUS,	123		Fertigkeitwiderstand
	APPLY_NORMAL_HIT_DEFEND_BONUS,	// 74	- POINT_NORMAL_HIT_DEFEND_BONUS,	124	Dursch. Schadenswiderstand
	APPLY_EXTRACT_HP_PCT,			// 75	- POINT_NONE
	APPLY_PC_BANG_EXP_BONUS,		// 76	- POINT_PC_BANG_EXP_BONUS,	125	iCafe EXP-Bonus
	APPLY_PC_BANG_DROP_BONUS,		// 77	- POINT_PC_BANG_DROP_BONUS,	126	iCafe Chance auf Erbeuten von Gegenständen
	APPLY_RESIST_WARRIOR,			// 78	- POINT_RESIST_WARRIOR,	59	Abwehr gegen Krieger
	APPLY_RESIST_ASSASSIN,			// 79	- POINT_RESIST_ASSASSIN,	60	Abwehr gegen Ninja
	APPLY_RESIST_SURA,				// 80	- POINT_RESIST_SURA,	61		Abwehr gegen Sura
	APPLY_RESIST_SHAMAN,			// 81	- POINT_RESIST_SHAMAN,	62	Abwehr gegen Schamanen
	APPLY_ENERGY,					// 82	- POINT_ENERGY,	128	Energie
	APPLY_DEF_GRADE,				// 83	- POINT_DEF_GRADE,	16	-- Keine Info
	APPLY_COSTUME_ATTR_BONUS,		// 84	- POINT_COSTUME_ATTR_BONUS,	130	Kostümbonus
	APPLY_MAGIC_ATTBONUS_PER,		// 85	- POINT_MAGIC_ATT_BONUS_PER,	131	Magischer Angriff
	APPLY_MELEE_MAGIC_ATTBONUS_PER,	// 86	- POINT_MELEE_MAGIC_ATT_BONUS_PER,	132	Magietrefferwiderstand in %
	APPLY_RESIST_ICE,				// 87	- POINT_RESIST_ICE,	133	Eiswiderstand
	APPLY_RESIST_EARTH,				// 88	- POINT_RESIST_EARTH,	134	Erdwiderstand
	APPLY_RESIST_DARK,				// 89	- POINT_RESIST_DARK,	135	Widerstand gegen Dunkelheit
	APPLY_ANTI_CRITICAL_PCT,		// 90	- POINT_RESIST_CRITICAL,	136	Widerstand gegen kritischen Treffer
	APPLY_ANTI_PENETRATE_PCT,		// 91	- POINT_RESIST_PENETRATE,	137	Widerstand gegen durchbohrenden Treffer
	APPLY_BLEEDING_REDUCE,			// 92	- POINT_BLEEDING_REDUCE,	138	Widerstand gegen Blutungsangriff
	APPLY_BLEEDING_PCT,				// 93	- POINT_BLEEDING_PCT,	139	Blutungsangriff
	APPLY_ATTBONUS_WOLFMAN,			// 94	- POINT_ATTBONUS_WOLFMAN,	140	Stark gegen Wolfman
	APPLY_RESIST_WOLFMAN,			// 95	- POINT_RESIST_WOLFMAN,	141	Abwehrchance gegen Lykaner
	APPLY_RESIST_CLAW,				// 96	- POINT_RESIST_CLAW,	142	Krallenwiderstand
	APPLY_ACCEDRAIN_RATE,			// 97	- POINT_ACCEDRAIN_RATE,	143	Aufnahmegrad
	APPLY_RESIST_MAGIC_REDUCTION,	// 98	- POINT_RESIST_MAGIC_REDUCTION,	144	Magiebruch
	APPLY_ENCHANT_ELECT,			// 99	- POINT_ENCHANT_ELECT,	145 Kraft der Blitze
	APPLY_ENCHANT_FIRE,				// 100	- POINT_ENCHANT_FIRE,	146 Kraft des Feuers
	APPLY_ENCHANT_ICE,				// 101	- POINT_ENCHANT_ICE,	147 Kraft des Eises
	APPLY_ENCHANT_WIND,				// 102	- POINT_ENCHANT_WIND,	148 Kraft des Windes
	APPLY_ENCHANT_EARTH,			// 103	- POINT_ENCHANT_EARTH,	149 Kraft der Erde
	APPLY_ENCHANT_DARK,				// 104	- POINT_ENCHANT_DARK,	150 Kraft der Dunkelheit
	APPLY_ATTBONUS_CZ,				// 105	- POINT_ATTBONUS_CZ,	151 Stark gegen Zodiakmonster
	APPLY_ATTBONUS_INSECT,			// 106	- POINT_ATTBONUS_INSECT,	152 Stark gegen Insekten
	APPLY_ATTBONUS_DESERT,			// 107	- POINT_ATTBONUS_DESERT,	52 Stark gegen Wüstenmonster
	APPLY_ATTBONUS_SWORD,			// 108	- POINT_ATTBONUS_SWORD,	152 Bruch von Schwertverteidigung
	APPLY_ATTBONUS_TWOHAND,			// 109	- POINT_ATTBONUS_TWOHAND,	153 Bruch von Zweihandverteidigung
	APPLY_ATTBONUS_DAGGER,			// 110	- POINT_ATTBONUS_DAGGER,	154 Bruch von Dolchverteidigung
	APPLY_ATTBONUS_BELL,			// 111	- POINT_ATTBONUS_BELL,	155 Bruch von Glockenverteidigung
	APPLY_ATTBONUS_FAN,				// 112	- POINT_ATTBONUS_FAN,	156 Bruch von Fächerverteidigung
	APPLY_ATTBONUS_BOW,				// 113	- POINT_ATTBONUS_BOW,	157 Bruch von Pfeilverteidigung
	APPLY_ATTBONUS_CLAW,			// 114	- POINT_ATTBONUS_CLAW,	158 Bruch von Krallenverteidigung
	APPLY_RESIST_HUMAN,				// 115	- POINT_RESIST_HUMAN,	159 Widerstand gegen Halbmenschen
	APPLY_RESIST_MOUNT_FALL,		// 116	- POINT_RESIST_MOUNT_FALL,	160 Widerstand gegen Sturz
	APPLY_RESIST_FIST,				// 117	- POINT_RESIST_FIST,	205 Widerstand gegen Fäuste
	APPLY_MOUNT,					// 118	- POINT_MOUNT,	109 -- Keine Info
#ifdef ENABLE_ATTR_6TH_7TH_EXTEND
	APPLY_SKILL_DAMAGE_SAMYEON = 119,	//Dreiwege-Schnitt-Schaden +%d%%	SA
	APPLY_SKILL_DAMAGE_TANHWAN = 120,
	APPLY_SKILL_DAMAGE_PALBANG = 121,
	APPLY_SKILL_DAMAGE_GIGONGCHAM = 122,
	APPLY_SKILL_DAMAGE_GYOKSAN = 123,
	APPLY_SKILL_DAMAGE_GEOMPUNG = 124,
	APPLY_SKILL_DAMAGE_AMSEOP = 125,
	APPLY_SKILL_DAMAGE_GUNGSIN = 126,
	APPLY_SKILL_DAMAGE_CHARYUN = 127,
	APPLY_SKILL_DAMAGE_SANGONG = 128,
	APPLY_SKILL_DAMAGE_YEONSA = 129,
	APPLY_SKILL_DAMAGE_KWANKYEOK = 130,
	APPLY_SKILL_DAMAGE_GIGUNG = 131,
	APPLY_SKILL_DAMAGE_HWAJO = 132,
	APPLY_SKILL_DAMAGE_SWAERYUNG = 133,
	APPLY_SKILL_DAMAGE_YONGKWON = 134,
	APPLY_SKILL_DAMAGE_PABEOB = 135,
	APPLY_SKILL_DAMAGE_MARYUNG = 136,
	APPLY_SKILL_DAMAGE_HWAYEOMPOK = 137,
	APPLY_SKILL_DAMAGE_MAHWAN = 138,
	APPLY_SKILL_DAMAGE_BIPABU = 139,
	APPLY_SKILL_DAMAGE_YONGBI = 140,
	APPLY_SKILL_DAMAGE_PAERYONG = 141,
	APPLY_SKILL_DAMAGE_NOEJEON = 142,
	APPLY_SKILL_DAMAGE_BYEURAK = 143,
	APPLY_SKILL_DAMAGE_CHAIN = 144,
	APPLY_SKILL_DAMAGE_CHAYEOL = 145,
	APPLY_SKILL_DAMAGE_SALPOONG = 146,
	APPLY_SKILL_DAMAGE_GONGDAB = 147,
	APPLY_SKILL_DAMAGE_PASWAE = 148,
	APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE = 149,
	APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE = 150,
	APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE = 151,
	APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE = 152,
	APPLY_HIT_BUFF_ENCHANT_FIRE = 153,
	APPLY_HIT_BUFF_ENCHANT_ICE = 154,
	APPLY_HIT_BUFF_ENCHANT_ELEC = 155,
	APPLY_HIT_BUFF_ENCHANT_WIND = 156,
	APPLY_HIT_BUFF_ENCHANT_DARK = 157,
	APPLY_HIT_BUFF_ENCHANT_EARTH = 158,
	APPLY_HIT_BUFF_RESIST_FIRE = 159,
	APPLY_HIT_BUFF_RESIST_ICE = 160,
	APPLY_HIT_BUFF_RESIST_ELEC = 161,
	APPLY_HIT_BUFF_RESIST_WIND = 162,
	APPLY_HIT_BUFF_RESIST_DARK = 163,
	APPLY_HIT_BUFF_RESIST_EARTH = 164,
	APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED = 165,
	APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED = 166,
	APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT = 167,
	APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS = 168,
	APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS = 169,
	APPLY_USE_SKILL_JEOKRANG_DEF_BONUS = 170,
	APPLY_USE_SKILL_GWIGEOM_DEF_BONUS = 171,
	APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS = 172,
	APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS = 173,
	APPLY_USE_SKILL_MANASHILED_CASTING_SPEED = 174,
	APPLY_USE_SKILL_HOSIN_DEF_BONUS = 175,
	APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS = 176,
	APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS = 177,
	APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS = 178,
	APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS = 179,
	APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED = 180,
	APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS = 181,
	APPLY_SKILL_DURATION_INCREASE_EUNHYUNG = 182,
	APPLY_SKILL_DURATION_INCREASE_GYEONGGONG = 183,
	APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG = 184,
	APPLY_SKILL_DURATION_INCREASE_JEOKRANG = 185,
	APPLY_USE_SKILL_PALBANG_HP_ABSORB = 186,
	APPLY_USE_SKILL_AMSEOP_HP_ABSORB = 187,
	APPLY_USE_SKILL_YEONSA_HP_ABSORB = 188,
	APPLY_USE_SKILL_YONGBI_HP_ABSORB = 189,
	APPLY_USE_SKILL_CHAIN_HP_ABSORB = 190,
	APPLY_USE_SKILL_PASWAE_SP_ABSORB = 191,
	APPLY_USE_SKILL_GIGONGCHAM_STUN = 192,
	APPLY_USE_SKILL_CHARYUN_STUN = 193,
	APPLY_USE_SKILL_PABEOB_STUN = 194,
	APPLY_USE_SKILL_MAHWAN_STUN = 195,
	APPLY_USE_SKILL_GONGDAB_STUN = 196,
	APPLY_USE_SKILL_SAMYEON_STUN = 197,
	APPLY_USE_SKILL_GYOKSAN_KNOCKBACK = 198,
	APPLY_USE_SKILL_SEOMJEON_KNOCKBACK = 199,
	APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK = 200,
	APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK = 201,
	APPLY_USE_SKILL_GONGDAB_KNOCKBACK = 202,
	APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK = 203,
	APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER = 204,
	APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER = 205,
	APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER = 206,
	APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER = 207,
	APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER = 208,
	APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER = 209,
	APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER = 210,
	APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER = 211,
	APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER = 212,
	APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER = 213,
	APPLY_ATTBONUS_STONE = 214,
	APPLY_DAMAGE_HP_RECOVERY = 215,
	APPLY_DAMAGE_SP_RECOVERY = 216,
	APPLY_ALIGNMENT_DAMAGE_BONUS = 217,
	APPLY_NORMAL_DAMAGE_GUARD = 218,
	APPLY_MORE_THEN_HP90_DAMAGE_REDUCE = 219,
	APPLY_USE_SKILL_TUSOK_HP_ABSORB = 220,
	APPLY_USE_SKILL_PAERYONG_HP_ABSORB = 221,
	APPLY_USE_SKILL_BYEURAK_HP_ABSORB = 222,
	APPLY_FIRST_ATTRIBUTE_BONUS = 223,
	APPLY_SECOND_ATTRIBUTE_BONUS = 224,
	APPLY_THIRD_ATTRIBUTE_BONUS = 225,
	APPLY_FOURTH_ATTRIBUTE_BONUS = 226,
	APPLY_FIFTH_ATTRIBUTE_BONUS = 227,
	APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER = 228,
	APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER = 229,
	APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER = 230,
	APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER = 231,
	APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER = 232,
	APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER = 233,
	APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER = 234,
	APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER = 235,
	APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER = 236,
	APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER = 237,
	APPLY_USE_SKILL_CHAYEOL_HP_ABSORB = 238,
	APPLY_SUNGMA_STR = 239,
	APPLY_SUNGMA_HP = 240,
	APPLY_SUNGMA_MOVE = 241,
	APPLY_SUNGMA_IMMUNE = 242,
	APPLY_HIT_PCT = 243,	//Präzision
	APPLY_RANDOM = 244,
	APPLY_ATTBONUS_PER_HUMAN = 245,
	APPLY_ATTBONUS_PER_ANIMAL = 246,
	APPLY_ATTBONUS_PER_ORC = 247,
	APPLY_ATTBONUS_PER_MILGYO = 248,
	APPLY_ATTBONUS_PER_UNDEAD = 249,
	APPLY_ATTBONUS_PER_DEVIL = 250,
	APPLY_ENCHANT_PER_ELECT = 251,
	APPLY_ENCHANT_PER_FIRE = 252,
	APPLY_ENCHANT_PER_ICE = 253,
	APPLY_ENCHANT_PER_WIND = 254,
	APPLY_ENCHANT_PER_EARTH = 255,
	APPLY_ENCHANT_PER_DARK = 256,
	APPLY_ATTBONUS_PER_CZ = 257,
	APPLY_ATTBONUS_PER_INSECT = 258,
	APPLY_ATTBONUS_PER_DESERT = 259,
	APPLY_ATTBONUS_PER_STONE = 260,
	APPLY_ATTBONUS_PER_MONSTER = 261,
	APPLY_RESIST_PER_HUMAN = 262,
	APPLY_RESIST_PER_ICE = 263,
	APPLY_RESIST_PER_DARK = 264,
	APPLY_RESIST_PER_EARTH = 265,
	APPLY_RESIST_PER_FIRE = 266,
	APPLY_RESIST_PER_ELEC = 267,
	APPLY_RESIST_PER_MAGIC = 268,
	APPLY_RESIST_PER_WIND = 269,
	APPLY_HIT_BUFF_SUNGMA_STR = 270,
	APPLY_HIT_BUFF_SUNGMA_MOVE = 271,
	APPLY_HIT_BUFF_SUNGMA_HP = 272,
	APPLY_HIT_BUFF_SUNGMA_IMMUNE = 273,
	APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER = 274,
	APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER = 275,
	APPLY_HIT_AUTO_HP_RECOVERY = 276,
	APPLY_HIT_AUTO_SP_RECOVERY = 277,
	APPLY_USE_SKILL_COOLTIME_DECREASE_ALL = 278,
	APPLY_HIT_STONE_ATTBONUS_STONE = 279,
	APPLY_HIT_STONE_DEF_GRADE_BONUS = 280,
	APPLY_KILL_BOSS_ITEM_BONUS = 281,
	APPLY_MOB_HIT_MOB_AGGRESSIVE = 282,
	APPLY_NO_DEATH_AND_HP_RECOVERY30 = 283,
	APPLY_AUTO_PICKUP = 284,
	APPLY_MOUNT_NO_KNOCKBACK = 285,
	APPLY_SUNGMA_PER_STR = 286,
	APPLY_SUNGMA_PER_HP = 287,
	APPLY_SUNGMA_PER_MOVE = 288,
	APPLY_SUNGMA_PER_IMMUNE = 289,
	APPLY_IMMUNE_POISON100 = 290,
	APPLY_IMMUNE_BLEEDING100 = 291,
	APPLY_MONSTER_DEFEND_BONUS = 292,
#endif

	MAX_APPLY_NUM,
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,				// Basic inventory. (2 pages of 45 spaces = 90 spaces)
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
	BELT_INVENTORY,			// NOTE: Belt inventory provided by the new belt slot item in W2.1 version
	GUILDBANK,
	MAIL,
	NPC_STORAGE,			//ENABLE_ATTR_6TH_7TH
	PREMIUM_PRIVATE_SHOP,
	ACCEREFINE,
	GROUND,
	PET_FEED,
	CHANGELOOK,
	AURA_REFINE,			//ENABLE_AURA_SYSTEM
#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
#endif
#ifdef ENABLE_ADDITIONAL_EQUIPMENT_PAGE
	ADDITIONAL_EQUIPMENT_1,
#endif

	WINDOW_TYPE_MAX
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE		= (1 << 0),
	AIFLAG_NOMOVE			= (1 << 1),
	AIFLAG_COWARD			= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB		= (1 << 6),
	AIFLAG_BERSERK			= (1 << 7),
	AIFLAG_STONESKIN		= (1 << 8),
	AIFLAG_GODSPEED			= (1 << 9),
	AIFLAG_DEATHBLOW		= (1 << 10),
	AIFLAG_REVIVE			= (1 << 11),
	AIFLAG_HEALER			= (1 << 12),	//ENABLE_DAWNMIST_DUNGEON
#ifdef ENABLE_PROTO_RENEWAL
	// Unknown Types
	AIFLAG_COUNT			= (1 << 13),
	AIFLAG_NORECOVERY		= (1 << 14),

	// Zodiac
	AIFLAG_REFLECT			= (1 << 15),
	AIFLAG_FALL				= (1 << 16),
	AIFLAG_VIT				= (1 << 17),
	AIFLAG_RATTSPEED		= (1 << 18),
	AIFLAG_RCASTSPEED		= (1 << 19),
	AIFLAG_RHP_REGEN		= (1 << 20),
	AIFLAG_TIMEVIT			= (1 << 21),
#endif
#ifdef ENABLE_SUNG_MAHI_TOWER
	AIFLAG_NOATTACK			= (1 << 22),
#else
	AIFLAG_UNK_22			= (1 << 22),
#endif
	AIFLAG_UNK_23			= (1 << 23),
	AIFLAG_UNK_24			= (1 << 24),
	AIFLAG_UNK_25			= (1 << 25),
	AIFLAG_ELEMENT_BUFF_NONE	= (1 << 26),
	AIFLAG_ELEMENT_BUFF_FIRE	= (1 << 27),
	AIFLAG_ELEMENT_BUFF_ICE		= (1 << 28),
	AIFLAG_ELEMENT_BUFF_ELECT	= (1 << 29),
	AIFLAG_ELEMENT_BUFF_WIND	= (1 << 30),
	AIFLAG_ELEMENT_BUFF_EARTH	= (1 << 31),
};

enum EAIFlags2
{
	AIFLAG_ELEMENT_BUFF_DARK = (1 << 0),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
#ifdef ENABLE_PROTO_RENEWAL
	UNK_IMMUNE_FLAG = (1 << 7),
	UNK_IMMUNE_FLAG1 = (1 << 8),
	UNK_IMMUNE_FLAG2 = (1 << 9),
	UNK_IMMUNE_FLAG3 = (1 << 10),
	UNK_IMMUNE_FLAG4 = (1 << 11),
	UNK_IMMUNE_FLAG5 = (1 << 12),
	UNK_IMMUNE_FLAG6 = (1 << 13),
	UNK_IMMUNE_FLAG7 = (1 << 14),
	UNK_IMMUNE_FLAG8 = (1 << 15),
#endif
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
#ifdef ENABLE_PROTO_RENEWAL
	MOB_RESIST_FIST,
#endif
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
#ifdef ENABLE_PROTO_RENEWAL
	MOB_RESIST_CLAW,		//ENABLE_WOLFMAN_CHARACTER
#endif
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
#ifdef ENABLE_PROTO_RENEWAL
	MOB_RESIST_BLEEDING,	//ENABLE_WOLFMAN_CHARACTER
#endif
	MOB_RESISTS_MAX_NUM
};

#ifdef ENABLE_PROTO_RENEWAL
enum EMobElementary
{
	MOB_ELEMENTAL_ELEC,
	MOB_ELEMENTAL_FIRE,
	MOB_ELEMENTAL_ICE,
	MOB_ELEMENTAL_WIND,
	MOB_ELEMENTAL_EARTH,
	MOB_ELEMENTAL_DARK,
	MOB_ELEMENTAL_MAX_NUM
};
#endif

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
/*
	SKILL_ATTR_TYPE_FIRE,
	SKILL_ATTR_TYPE_ICE,
	SKILL_ATTR_TYPE_ELEC,
	SKILL_ATTR_TYPE_DARK,
	*/
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
/*	GUILD_WAR_TYPE_TIGER,
	GUILD_WAR_TYPE_DEFENSE,
	GUILD_WAR_TYPE_TIME*/

	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60,
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

#if defined(ENABLE_GUILDRENEWAL_SYSTEM) || defined(ENABLE_GUILDBANK_LOG)
enum EGuildLogInOut
{
	GUILD_GOLD_TYPE_IN = 0,						// Einzahlung
	GUILD_GOLD_TYPE_OUT = 1,					// Auszahlung
	//GUILD_GOLD_TYPE_PROMOTE = 2,				// Werbung [unused]
	//GUILD_GOLD_TYPE_PROMOTE_UPDATE = 3,		// Werbung [unused]
	//GUILD_GOLD_TYPE_OBJECT_CHANGE = 4,		// Umbau [unused]
	GUILD_GOLD_TYPE_OBJECT_CREATE = 5,			// Gebäudebau
	GUILD_GOLD_TYPE_DRAGON_SP_RECOVER = 6,		// Drachenmacht
	GUILD_GOLD_TYPE_BUY_GUILD_LAND = 7,			// Landkauf
	GUILD_GOLD_TYPE_CHANGE_SMELTER = 8,			// Ofen-Umbau
	GUILD_GOLD_TYPE_UPGRADE_ALTEROFPOWER = 9,	// Altar-Ausbau
	GUILD_GOLD_TYPE_UPGRADE_GUILDBANK = 10,		// Bank-Ausbau
	//GUILD_GOLD_TYPE_DEAL_GUILD_LAND = 11		// Landverkauf [unused]
};

enum EGuildLogItemInOut
{
	GUILD_ITEM_TYPE_IN = 0,
	GUILD_ITEM_TYPE_OUT = 1
};
#endif

enum EAttributeSet
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY,
	ATTRIBUTE_SET_WRIST,
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
#if defined(ENABLE_PENDANT) && defined(ENABLE_PENDANT_ITEM_ATTR)
	ATTRIBUTE_SET_PENDANT,
#endif
#if defined(ENABLE_GLOVE_SYSTEM) && defined(ENABLE_GLOVE_ITEM_ATTR)
	ATTRIBUTE_SET_GLOVE,
#endif
#ifdef ENABLE_ITEM_ATTR_COSTUME
	ATTRIBUTE_SET_COSTUME_BODY,
	ATTRIBUTE_SET_COSTUME_HAIR,
#if defined(ENABLE_ITEM_ATTR_COSTUME) && defined(ENABLE_WEAPON_COSTUME_SYSTEM)
	ATTRIBUTE_SET_COSTUME_WEAPON,
#endif
#endif
	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,
	PREMIUM_ITEM,
	PREMIUM_SAFEBOX,
	PREMIUM_AUTOLOOT,
	PREMIUM_FISH_MIND,
	PREMIUM_MARRIAGE_FAST,
	PREMIUM_GOLD,
//#ifdef ENABLE_AUTO_SYSTEM
	PREMIUM_AUTO_USE,
//#endif
//#ifdef ENABLE_YOHARA_SYSTEM
	PREMIUM_SUNGMA,
//#endif
//#ifdef ENABLE_PREMIUM_PRIVATE_SHOP
	PREMIUM_PREMIUM_PRIVATE_SHOP,
//#endif
	PREMIUM_MAX_NUM
};

enum SPECIAL_EFFECT
{
	SE_NONE,
	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,
	SE_AUTO_HPUP,
	SE_AUTO_SPUP,
	SE_EQUIP_RAMADAN_RING,
	SE_EQUIP_HALLOWEEN_CANDY,
	SE_EQUIP_HAPPINESS_RING,
	SE_EQUIP_LOVE_PENDANT,
	SE_CAPE_OF_COURAGE_EFFECT,	//@fixme510
	SE_EQUIP_BOOTS,
	SE_EQUIP_HEROMEDAL,
	SE_EQUIP_CHOCOLATE_AMULET,
	SE_EQUIP_EMOTION_MASK,
	SE_EQUIP_WILLPOWER_RING,
	SE_EQUIP_DEADLYPOWER_RING,
	SE_EQUIP_EASTER_CANDY_EQIP,
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	SE_ACCE_SUCESS_ABSORB,
	SE_ACCE_EQUIP,
	SE_ACCE_BACK,
#endif
#ifdef ENABLE_DAWNMIST_DUNGEON
	SE_HEAL,
#endif
#ifdef ENABLE_ANTI_EXP_RING
	SE_AUTO_EXP,
#endif
#ifdef ENABLE_12ZI
	SE_SKILL_DAMAGE_ZONE,
	SE_SKILL_SAFE_ZONE,

	SE_METEOR,
	SE_BEAD_RAIN,
	SE_FALL_ROCK,
	SE_ARROW_RAIN,
	SE_HORSE_DROP,
	SE_EGG_DROP,
	SE_DEAPO_BOOM,

	SE_SKILL_DAMAGE_ZONE_BIG,
	SE_SKILL_DAMAGE_ZONE_MIDDLE,
	SE_SKILL_DAMAGE_ZONE_SMALL,

	SE_SKILL_SAFE_ZONE_BIG,
	SE_SKILL_SAFE_ZONE_MIDDLE,
	SE_SKILL_SAFE_ZONE_SMALL,
#endif
#ifdef ENABLE_BATTLE_FIELD
	SE_EFFECT_BATTLE_POTION,
#endif
#ifdef ENABLE_GUILD_DRAGONLAIR_SYSTEM
	SE_DRAGONLAIR_STONE_UNBEATABLE_1,
	SE_DRAGONLAIR_STONE_UNBEATABLE_2,
	SE_DRAGONLAIR_STONE_UNBEATABLE_3,
#endif
#ifdef ENABLE_FLOWER_EVENT
	SE_FLOWER_EVENT,
#endif
#ifdef ENABLE_GEM_SYSTEM
	SE_GEM_PENDANT,
#endif
#ifdef ENABLE_QUEEN_NETHIS
	SE_EFFECT_SNAKE_REGEN,
#endif
#ifdef ENABLE_BATTLE_PASS_SYSTEM
	SE_EFFECT_BP_NORMAL_MISSION_COMPLETED,
	SE_EFFECT_BP_PREMIUM_MISSION_COMPLETED,
	SE_EFFECT_BP_EVENT_MISSION_COMPLETED,
	SE_EFFECT_BP_NORMAL_BATTLEPASS_COMPLETED,
	SE_EFFECT_BP_PREMIUM_BATTLEPASS_COMPLETED,
	SE_EFFECT_BP_EVENT_BATTLEPASS_COMPLETED,
#endif
};

enum EWeekDays
{
	MONDAY = 1,
	TUESDAY = 2,
	WEDNESDAY = 3,
	THURSDAY = 4,
	FRIDAY = 5,
	SATURDAY = 6,
	SUNDAY = 0,
};

enum EHours
{
	TIME_DAY,
	TIME_HOUR,
	TIME_MIN,
	TIME_SEC
};

enum MapTypes
{
	MAP_A1						= 1,	// Rotes Reich Map 1			metin2_map_a1
	MAP_A3						= 3,	// Rotes Reich Map 2			metin2_map_a3
	MAP_GUILD_01				= 4,	// Gildenland Rotes Reich		metin2_map_guild_01
	MAP_MONKEY_DUNGEON_11		= 5,	// Affendungeon (Leicht)		metin2_map_monkey_dungeon_11
	GUILD_VILLAGE_01			= 6,	// Gildenland 1					metin2_guild_village_01
	MAP_B1						= 21,	// Gelbes Reich Map 1			metin2_map_b1
	MAP_B3						= 23,	// Gelbes Reich Map 2			metin2_map_b3
	MAP_GUILD_02				= 24,	// Gildenland Gelbes Reich		metin2_map_guild_02
	MAP_MONKEY_DUNGEON_12		= 25,	// Affendungeon (Mittel)		metin2_map_monkey_dungeon_12
	GUILD_VILLAGE_02			= 26,	// Gildenland 2					metin2_guild_village_02
	MAP_C1						= 41,	// Blaues Reich Map 1			metin2_map_c1
	MAP_C3						= 43,	// Blaues Reich Map 2			metin2_map_c3
	MAP_GUILD_03				= 44,	// Gildenland Blaues Reich		metin2_map_guild_03
	MAP_MONKEY_DUNGEON_13		= 45,	// Affendungeon (Schwer)		metin2_map_monkey_dungeon_13
	GUILD_VILLAGE_03			= 46,	// Gildenland 3					metin2_guild_village_03
	MAP_N_SNOWM_01				= 61,	// Eisland (Berg Sohan)			map_n_snowm_01
	MAP_N_FLAME_01				= 62,	// Feuerland					metin2_map_n_flame_01
	MAP_N_DESERT_01				= 63,	// Yongbi Wüste					metin2_map_n_desert_01
	MAP_N_THREEWAY				= 64,	// Orktal						map_n_threeway
	MAP_MILGYO					= 65,	// Hwang Tempel					metin2_map_milgyo
	MAP_DEVILTOWER1				= 66,	// Dämonenturm					metin2_map_deviltower1
	MAP_TRENT					= 67,	// Geisterwald					metin2_map_trent
	MAP_TRENT02					= 68,	// Roter Wald					metin2_map_trent02
	MAP_WL_01					= 69,	//								metin2_map_WL_01
	MAP_NUSLUCK01				= 70,	//								metin2_map_nusluck01
	MAP_SPIDERDUNGEON_02		= 71,	// Spinnendungeon 2				metin2_map_spiderdungeon_02
	MAP_SKIPIA_DUNGEON_01		= 72,	// Grotte I						metin2_map_skipia_dungeon_01
	MAP_SKIPIA_DUNGEON_02		= 73,	// Grotte II					metin2_map_skipia_dungeon_02
	MAP_WEDDING_01				= 81,	// Hochzeitsmap					metin2_map_wedding_01
	MAP_PVP_ARENA				= 90,	//								metin2_map_pvp_arena
	MAP_E1_A					= 91,	// Wolfman Rotes Portal			metin2_map_wolf_a1
	MAP_E1_B					= 92,	// Wolfman Gelbes Portal		metin2_map_wolf_b1
	MAP_E1_C					= 93,	// Wolfman Blaues Portal		metin2_map_wolf_c1
	MAP_T1						= 103,	// 								metin2_map_t1
	MAP_SPIDERDUNGEON			= 104,	// Spinnendungeon 1				metin2_map_spiderdungeon
	MAP_T2						= 105,	//								metin2_map_t2
	MAP_MONKEY_DUNGEON			= 107,	// Affendoungen anfänger		metin2_map_monkey_dungeon
	MAP_MONKEY_DUNGEON2			= 108,	// Affendoungen normal			metin2_map_monkey_dungeon2
	MAP_MONKEY_DUNGEON3			= 109,	// Affendoungen schwer			metin2_map_monkey_dungeon3
	MAP_T3						= 110,	//								metin2_map_t3
	MAP_T4						= 111,	//								metin2_map_t4
	MAP_DUEL					= 112,	// Duellier Map 1gg1			metin2_map_duel
	MAP_OXEVENT					= 113,	// Ox-Event Map					metin2_map_oxevent
	MAP_SUNGZI					= 114,	// Reichsschlacht Map (Normal)	metin2_map_sungzi
	MAP_SUNGZI_FLAME_HILL_01	= 118,	// Reichsschlacht Map (Feuer)	metin2_map_sungzi_flame_hill_01
	MAP_SUNGZI_FLAME_HILL_02	= 119,	// Reichsschlacht Map (Feuer)	metin2_map_sungzi_flame_hill_02
	MAP_SUNGZI_FLAME_HILL_03	= 120,	// Reichsschlacht Map (Feuer)	metin2_map_sungzi_flame_hill_03
	MAP_SUNGZI_SNOW				= 121,	// Reichsschlacht Map (Schnee)	metin2_map_sungzi_snow
	MAP_SUNGZI_SNOW_PASS01		= 122,	// Reichsschlacht Map (Schnee)	metin2_map_sungzi_snow_pass01
	MAP_SUNGZI_SNOW_PASS02		= 123,	// Reichsschlacht Map (Schnee)	metin2_map_sungzi_snow_pass02
	MAP_SUNGZI_SNOW_PASS03		= 124,	// Reichsschlacht Map (Schnee)	metin2_map_sungzi_snow_pass03
	MAP_SUNGZI_DESERT_01		= 125,	// Reichsschlacht Map (Wüste)	metin2_map_sungzi_desert_01
	MAP_SUNGZI_DESERT_HILL_01	= 126,	// Reichsschlacht Map (Wüste)	metin2_map_sungzi_desert_hill_01
	MAP_SUNGZI_DESERT_HILL_02	= 127,	// Reichsschlacht Map (Wüste)	metin2_map_sungzi_desert_hill_02
	MAP_SUNGZI_DESERT_HILL_03	= 128,	// Reichsschlacht Map (Wüste)	metin2_map_sungzi_desert_hill_03
	MAP_GUILD_WAR_1				= 130,	//								metin2_guild_war1
	MAP_GUILD_WAR_2				= 131,	//								metin2_guild_war2
	MAP_GUILD_WAR_3				= 132,	//								metin2_guild_war3
	MAP_GUILD_WAR_4				= 133,	//								metin2_guild_war4
	MAP_GM_GUILD				= 180,	// GM-Map						gm_guild_build
	MAP_EMPIREWAR01				= 181,	// Reichsschlacht 1				metin2_map_empirewar01
	MAP_EMPIREWAR02				= 182,	// Reichsschlacht 2				metin2_map_empirewar02
	MAP_EMPIREWAR03				= 183,	// Reichsschlacht 3				metin2_map_empirewar03
	MAP_SKIPIA_DUNGEON_BOSS		= 208,	// Grotte (Boss)				metin2_map_skipia_dungeon_boss
	MAP_DEVILCATACOMB			= 216,	// Teufelskatakomben			metin2_map_devilcatacomb
	MAP_SPIDERDUNGEON_03		= 217,	// Spinnendungeon 3				metin2_map_spiderdungeon_03
	MAP_CAPEDRAGONHEAD			= 301,	// Kap des Drachenfeuer			Metin2_map_CapeDragonHead
	MAP_DAWNMISTWOOD			= 302,	// Nephritbucht					metin2_map_dawnmistwood
	MAP_BAYBLACKSAND			= 303,	// Gautamakliff					metin2_map_BayBlackSand
	MAP_MT_THUNDER				= 304,	// Donnerberge					metin2_map_Mt_Thunder
	MAP_N_FLAME_DUNGEON_01		= 351,	// Blazing Pugatory				metin2_map_n_flame_dungeon_01
	MAP_N_SNOW_DUNGEON_01		= 352,	// Nemeres						metin2_map_n_snow_dungeon_01
	MAP_DAWNMISTWOOD_DUNGEON	= 353,	// Verwunschener Wald			metin2_map_dawnmist_dungeon_01
	MAP_MT_THUNDER_DUNGEON		= 354,	// Tempel der Ochao				metin2_map_mt_th_dungeon_01
	MAP_12ZI_STAGE				= 355,	// Zodiak						metin2_12zi_stage
	MAP_N_FLAME_DRAGON			= 356,	// 								metin2_map_n_flame_dragon
	MAP_BATTLEFIELD				= 357,	// Combat Zone					metin2_map_battlefied
	MAP_DEFENSEWAVE				= 358,	// Hydra						metin2_map_defensewave
	MAP_DEFENSEWAVE_PORT		= 359,	// Hydra						metin2_map_defensewave_port
	MAP_MISTS_OF_ISLAND			= 360,	//								metin2_map_mists_of_island
	MAP_MINIBOSS_01				= 361,	//								metin2_map_miniboss_01
	MAP_MINIBOSS_02				= 362,	//								metin2_map_miniboss_02
	MAP_LABYRINTH				= 363,	//								metin2_map_labyrinth
	MAP_BOSS_CRACK_SKIPIA		= 364,	//								metin2_map_boss_crack_skipia
	MAP_BOSS_CRACK_FLAME		= 365,	//								metin2_map_boss_crack_flame
	MAP_BOSS_CRACK_SNOW			= 366,	//								metin2_map_boss_crack_snow
	MAP_BOSS_CRACK_DAWNMIST		= 367,	//								metin2_map_boss_crack_dawnmist
	MAP_BOSS_AWAKEN_SKIPIA		= 368,	//								metin2_map_boss_awaken_skipia
	MAP_BOSS_AWAKEN_FLAME		= 369,	//								metin2_map_boss_awaken_flame
	MAP_BOSS_AWAKEN_SNOW		= 370,	//								metin2_map_boss_awaken_snow
	MAP_BOSS_AWAKEN_DAWNMIST	= 371,	//								metin2_map_boss_awaken_dawnmist
	MAP_GUILD_PVE				= 372,	//								metin2_guild_pve
	MAP_EASTPLAIN_01			= 373,	// 								metin2_map_eastplain_01
	MAP_EMPIRECASTLE			= 374,	// 								metin2_map_empirecastle
	MAP_BATTLEROYALE			= 375,	//								metin2_map_battleroyale
	MAP_EASTPLAIN_02			= 376,	// 								metin2_map_eastplain_02
	MAP_EASTPLAIN_03			= 377,	// 								metin2_map_eastplain_03
	MAP_ELEMENTAL_01			= 378,	// 								metin2_map_elemental_01
	MAP_ELEMENTAL_02			= 379,	// 								metin2_map_elemental_02
	MAP_ELEMENTAL_03			= 380,	// 								metin2_map_elemental_03
	MAP_ELEMENTAL_04			= 381,	//								metin2_map_elemental_04
	MAP_MAZE_DUNGEON1			= 382,	// 								metin2_map_maze_dungeon1
	MAP_MAZE_DUNGEON2			= 383,	// 								metin2_map_maze_dungeon2
	MAP_MAZE_DUNGEON3			= 384,	// 								metin2_map_maze_dungeon3
	MAP_SNAKEVALLEY				= 385,	//								metin2_map_snakevalley
	MAP_SMG_DUNGEON_01			= 386,	// 								metin2_map_smhdungeon_01
	MAP_SMG_DUNGEON_02			= 387,	// 								metin2_map_smhdungeon_02
	MAP_ICECRYSTALCAVE			= 388,	//								metin2_map_icecrystalcave
	MAP_WHITDRAGONVALLEY		= 389,	//								metin2_map_whitdragonvalley
	MAP_SNAKE_TEMPLE_01			= 390,	//								metin2_map_snake_temple_01
	MAP_SNAKE_TEMPLE_02			= 391,	//								metin2_map_snake_temple_02
	MAP_PRIVATSHOP				= 392,	// Priv. Shop					metin2_map_privateshop
	MAP_WHITEDRAGONCAVE_01		= 393,	//								metin2_map_whitedragoncave_01
	MAP_WHITEDRAGONCAVE_02		= 394,	//								metin2_map_whitedragoncave_02
	MAP_WHITEDRAGONCAVE_BOSS	= 395,	//								metin2_map_whitedragoncave_boss
	MAP_ANGLAR_DUNGEON			= 396,	//								metin2_map_anglar_dungeon_01
	MAP_OTHERWORLD_01			= 400,	//								metin2_map_otherworld_01
	MAP_OTHERWORLD_02			= 401,	//								metin2_map_otherworld_02
	MAP_OTHERWORLD_03			= 402,	//								metin2_map_otherworld_03
	MAP_OTHERWORLD_04			= 403,	//								metin2_map_otherworld_04
};

#include "item_length.h"

// Structure representing the position of inventory
// The reason there is an implicit cast to int is,
// Because all inventory-related functions did not receive window_type, but only received one cell (because there was only one inventory, and inventory type was not necessary)
// It is difficult to modify all the function calls related to inventory.

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

#ifdef ENABLE_SPECIAL_INVENTORY
enum ESpecialInventory
{
	SPECIAL_INVENTORY_TYPE_SKILLBOOK,
	SPECIAL_INVENTORY_TYPE_STONE,
	SPECIAL_INVENTORY_TYPE_MATERIAL,
	SPECIAL_INVENTORY_TYPE_COUNT,

	SPECIAL_INVENTORY_WIDTH = 5,
	SPECIAL_INVENTORY_HEIGHT = 9,
	SPECIAL_INVENTORY_PAGE_SIZE = SPECIAL_INVENTORY_WIDTH * SPECIAL_INVENTORY_HEIGHT,
	SPECIAL_INVENTORY_SLOT_COUNT = SPECIAL_INVENTORY_PAGE_SIZE * SPECIAL_INVENTORY_TYPE_COUNT,
};
#endif

enum EMisc2
{
	DRAGON_SOUL_EQUIP_SLOT_START = WEAR_MAX_NUM,
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),

	INVENTORY_SLOT_START = 0,
#    ifndef ENABLE_SPECIAL_INVENTORY
	INVENTORY_SLOT_COUNT = INVENTORY_MAX_NUM,
#    endif

	EQUIPMENT_SLOT_START = 0,
	EQUIPMENT_SLOT_COUNT = WEAR_MAX_NUM + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),

	BELT_INVENTORY_SLOT_START = 0,
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_COUNT,

#ifdef ENABLE_SPECIAL_INVENTORY
	SPECIAL_INVENTORY_SLOT_START = INVENTORY_MAX_NUM,
	SPECIAL_INVENTORY_SKILLBOOK_START = SPECIAL_INVENTORY_SLOT_START,
	SPECIAL_INVENTORY_SKILLBOOK_END = SPECIAL_INVENTORY_SKILLBOOK_START + SPECIAL_INVENTORY_PAGE_SIZE * INVENTORY_PAGE_COUNT,
	SPECIAL_INVENTORY_STONE_START = SPECIAL_INVENTORY_SKILLBOOK_END,
	SPECIAL_INVENTORY_STONE_END = SPECIAL_INVENTORY_STONE_START + SPECIAL_INVENTORY_PAGE_SIZE * INVENTORY_PAGE_COUNT,
	SPECIAL_INVENTORY_MATERIAL_START = SPECIAL_INVENTORY_STONE_END,
	SPECIAL_INVENTORY_MATERIAL_END = SPECIAL_INVENTORY_MATERIAL_START + SPECIAL_INVENTORY_PAGE_SIZE * INVENTORY_PAGE_COUNT,
	SPECIAL_INVENTORY_SLOT_END = SPECIAL_INVENTORY_MATERIAL_END,

	INVENTORY_SLOT_COUNT = SPECIAL_INVENTORY_SLOT_END,
#endif

	WEAR_SLOT_END = WEAR_MAX_NUM + DRAGON_SOUL_EQUIP_SLOT_END,
};

#ifdef ENABLE_ADDITIONAL_EQUIPMENT_PAGE 
enum EIndexNewEquipment
{
	NEW_EQUIPMENT_PAGE_1,
	NEW_EQUIPMENT_PAGE_2,
	NEW_EQUIPMENT_MAX_PAGE,
};

enum AdditionalEquipmentConfig
{
	ADDITIONAL_EQUIPMENT_MAX_SLOT = WEAR_MAX_NUM,
};

enum ENewEquipment
{
	PAGE_EQUIPMENT_ACTUAL, // save page select player
	PAGE_EQUIPMENT_TOTAL, // save count page unlock player
	PART_MAX_NEW_EQUIPMENT,
};
#endif

#pragma pack(push, 1)

typedef struct SItemPos
{
	uint8_t window_type;
	uint16_t cell;
	SItemPos() noexcept
	{
		window_type = INVENTORY;
		cell = WORD_MAX;
	}

	SItemPos(uint8_t _window_type, uint16_t _cell) noexcept
	{
		window_type = _window_type;
		cell = _cell;
	}

	bool IsValidItemPosition() const noexcept
	{
		switch (window_type)
		{
			case RESERVED_WINDOW:
				return false;

			case INVENTORY:
				return cell < (INVENTORY_SLOT_COUNT);

			case EQUIPMENT:
				return cell < (EQUIPMENT_SLOT_COUNT);

			case BELT_INVENTORY:
				return cell < (BELT_INVENTORY_SLOT_COUNT);

			case DRAGON_SOUL_INVENTORY:
				return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);

#ifdef ENABLE_SWITCHBOT
			case SWITCHBOT:
				return cell < (SWITCHBOT_SLOT_COUNT);
#endif

#ifdef ENABLE_ATTR_6TH_7TH
			case NPC_STORAGE:
				return cell < (NPC_STORAGE_SLOT_COUNT);
#endif

#ifdef ENABLE_ADDITIONAL_EQUIPMENT_PAGE
			case ADDITIONAL_EQUIPMENT_1:
				return cell < (ADDITIONAL_EQUIPMENT_MAX_SLOT);
#endif

			// A window that is dynamically sized cannot be checked for validity.
			case SAFEBOX:
			case MALL:
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
			case GUILDBANK:
#endif
				return false;

			default:
				sys_err("Invalid window type %d", window_type);
				return false;
		}

		return false;
	}

	bool IsEquipPosition() const noexcept
	{
		return (IsEquipmentEquipPosition() || IsDragonSoulEquipPosition());
	}
	bool IsEquipmentEquipPosition() const noexcept
	{
		return (EQUIPMENT == window_type && cell >= 0 && cell < WEAR_MAX_NUM);
	}
	bool IsDragonSoulEquipPosition() const noexcept
	{
		return (EQUIPMENT == window_type && cell >= DRAGON_SOUL_EQUIP_SLOT_START && cell < DRAGON_SOUL_EQUIP_SLOT_END);
	}
	bool IsBeltInventoryPosition() const noexcept
	{
		return (BELT_INVENTORY == window_type && cell >= BELT_INVENTORY_SLOT_START && cell < BELT_INVENTORY_SLOT_END);
	}
	bool IsDefaultInventoryPosition() const noexcept
	{
		return (INVENTORY == window_type && cell < INVENTORY_MAX_NUM);
	}

#ifdef ENABLE_SWITCHBOT
	bool IsSwitchbotPosition() const noexcept
	{
		return ((SWITCHBOT == window_type) && (cell < SWITCHBOT_SLOT_COUNT));
	}
#endif

#ifdef ENABLE_SPECIAL_INVENTORY
	bool IsSpecialInventoryPosition() const noexcept
	{
		return ((INVENTORY == window_type) && (cell >= SPECIAL_INVENTORY_SLOT_START && cell < SPECIAL_INVENTORY_SLOT_END));
	}

	int GetSpecialInventoryType() noexcept
	{
		if ((cell >= SPECIAL_INVENTORY_SKILLBOOK_START) && (cell < SPECIAL_INVENTORY_SKILLBOOK_END))
		{
			return SPECIAL_INVENTORY_TYPE_SKILLBOOK;
		}
		else if ((cell >= SPECIAL_INVENTORY_STONE_START) && (cell < SPECIAL_INVENTORY_STONE_END))
		{
			return SPECIAL_INVENTORY_TYPE_STONE;
		}
		else if ((cell >= SPECIAL_INVENTORY_MATERIAL_START) && (cell < SPECIAL_INVENTORY_MATERIAL_END))
		{
			return SPECIAL_INVENTORY_TYPE_MATERIAL;
		}
		else
		{
			return -1;
		}
	}
#endif

#ifdef ENABLE_ADDITIONAL_EQUIPMENT_PAGE
	bool IsAdditionalEquipment1() const noexcept
	{
		return ((ADDITIONAL_EQUIPMENT_1 == window_type) && (cell < ADDITIONAL_EQUIPMENT_MAX_SLOT));
	}
#endif

	bool operator == (const struct SItemPos& rhs) const noexcept
	{
		return ((window_type == rhs.window_type) && (cell == rhs.cell));
	}

//#ifdef ENABLE_PREMIUM_PRIVATE_SHOP
	bool operator != (const struct SItemPos& rhs) const noexcept
	{
		return ((window_type != rhs.window_type) || (cell != rhs.cell));
	}
//#endif

	bool operator < (const struct SItemPos& rhs) const noexcept
	{
		return ((window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell)));
	}
} TItemPos;

const TItemPos NPOS(RESERVED_WINDOW, WORD_MAX);

#ifdef ENABLE_SPECIAL_INVENTORY
struct SpecialInventoryRange
{
	uint8_t type;
	uint16_t start;
	uint16_t end;

	SpecialInventoryRange() noexcept
	{
		type = 0;
		start = 0;
		end = 0;
	}

	SpecialInventoryRange(uint8_t _type, uint16_t _start, uint16_t _end) noexcept
	{
		type = _type;
		start = _start;
		end = _end;

		if (type == SPECIAL_INVENTORY_TYPE_SKILLBOOK)
		{
			start = SPECIAL_INVENTORY_SKILLBOOK_START;
			end = SPECIAL_INVENTORY_SKILLBOOK_END;
		}
		else if (type == SPECIAL_INVENTORY_TYPE_STONE)
		{
			start = SPECIAL_INVENTORY_STONE_START;
			end = SPECIAL_INVENTORY_STONE_END;
		}
		else if (type == SPECIAL_INVENTORY_TYPE_MATERIAL)
		{
			start = SPECIAL_INVENTORY_MATERIAL_START;
			end = SPECIAL_INVENTORY_MATERIAL_END;
		}
	}
};
#endif

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
#ifdef ENABLE_RENEWAL_SHOPEX
	SHOP_COINT_TYPE_ITEM,
	SHOP_COINT_TYPE_EXP,
#endif
#ifdef ENABLE_BATTLE_FIELD
	SHOP_COIN_TYPE_BATTLE_POINT,
#endif
#ifdef ENABLE_10TH_EVENT
	SHOP_COIN_TYPE_10TH_EVENT,
#endif
#ifdef ENABLE_MEDAL_OF_HONOR
	SHOP_COIN_TYPE_MEDAL_OF_HONOR,
#endif
#ifdef ENABLE_MINI_GAME_BNW
	SHOP_COIN_TYPE_BNW,
#endif
#ifdef ENABLE_ACHIEVEMENT_SYSTEM
	SHOP_COIN_TYPE_ACHIEVEMENT,
#endif
	SHOP_COIN_TYPE_MAX
} EShopCoinType;

#ifdef ENABLE_SKILL_COLOR_SYSTEM
namespace ESkillColorLength
{
	enum ESkillColorLength
	{
#	ifdef ENABLE_NINETH_SKILL
		MAX_SKILL_COUNT = 9,
#	else
		MAX_SKILL_COUNT = 6,
#	endif
		MAX_EFFECT_COUNT = 5,
#	if defined(ENABLE_WOLFMAN_CHARACTER) && defined(ENABLE_NINETH_SKILL)
		MAX_BUFF_COUNT = 7,
#	elif defined(ENABLE_WOLFMAN_CHARACTER) && !defined(ENABLE_NINETH_SKILL)
		MAX_BUFF_COUNT = 6,
#	else
		MAX_BUFF_COUNT = 5,
#	endif
		BUFF_BEGIN = MAX_SKILL_COUNT,
	};
}
#endif

#ifdef ENABLE_REFINE_ELEMENT
enum ERefineElement
{
	MAX_ELEMENTS_SPELL = 3,
	GOLD_DOWNGRADE_BONUS_ELEMENTS_SPELL = 10000000,
	GOLD_ADD_BONUS_ELEMENTS_SPELL = 3000000,
	GOLD_CHANGE_BONUS_ELEMENTS_SPELL = 10000000,
	ATTACK_RANGE_BONUS_ELEMENTS_SPELL_MIN = 2,
	ATTACK_RANGE_BONUS_ELEMENTS_SPELL_MAX = 12,
	VALUES_RANGE_BONUS_ELEMENTS_SPELL_MIN = 1,
	VALUES_RANGE_BONUS_ELEMENTS_SPELL_MAX = 8,
};
#endif

#ifdef ENABLE_EXTEND_INVEN_ITEM_UPGRADE
enum EExtendInvenMisc
{
	INVENTORY_OPEN_KEY_GOLD = 72319,
	INVENTORY_OPEN_KEY_SILVER = 72320,

	INVENTORY_NEED_KEY_START = 2,
	INVENTORY_NEED_KEY_INCREASE = 3, // increase the number of keys in each 3 stages. you can change
	INVENTORY_OPEN_PAGE_COUNT = 2,

	INVENTORY_OPEN_PAGE_SIZE = INVENTORY_OPEN_PAGE_COUNT * INVENTORY_PAGE_SIZE,
	INVENTORY_LOCKED_PAGE_COUNT = INVENTORY_PAGE_COUNT - INVENTORY_OPEN_PAGE_COUNT,
	INVENTORY_LOCK_COVER_COUNT = INVENTORY_LOCKED_PAGE_COUNT * INVENTORY_PAGE_ROW
};

# ifdef ENABLE_EXTEND_INVEN_ITEM_UPGRADE_SPECIAL_INV
enum EExtendSpecialInvenMisc
{
	SPECIAL_INVENTORY_OPEN_PAGE_COUNT = 1,
	SPECIAL_INVENTORY_OPEN_PAGE_SIZE = SPECIAL_INVENTORY_OPEN_PAGE_COUNT * SPECIAL_INVENTORY_PAGE_SIZE,
	SPECIAL_INVENTORY_LOCKED_PAGE_COUNT = INVENTORY_PAGE_COUNT - SPECIAL_INVENTORY_OPEN_PAGE_COUNT,
	SPECIAL_INVENTORY_LOCK_COVER_COUNT = SPECIAL_INVENTORY_LOCKED_PAGE_COUNT * SPECIAL_INVENTORY_HEIGHT,
};
# endif

enum EExtendInvenResult
{
	EX_INVEN_FAIL_FALL_SHORT = 0,
	EX_INVEN_SUCCESS = 1,
	EX_INVEN_FAIL_FOURTH_PAGE_STAGE_MAX = 2,
};
#endif

#ifdef ENABLE_AURA_SYSTEM
typedef struct SAuraRefineInfo
{
	uint8_t bAuraRefineInfoLevel;
	uint8_t bAuraRefineInfoExpPercent;
} TAuraRefineInfo;

enum EAuraMisc
{
	AURA_MAX_LEVEL = 250,
	AURA_REFINE_MAX_DISTANCE = 1000,
};

enum EAuraWindowType
{
	AURA_WINDOW_TYPE_ABSORB,
	AURA_WINDOW_TYPE_GROWTH,
	AURA_WINDOW_TYPE_EVOLVE,
	AURA_WINDOW_TYPE_MAX,
};

enum EAuraSlotType
{
	AURA_SLOT_MAIN,
	AURA_SLOT_SUB,
	AURA_SLOT_RESULT,
	AURA_SLOT_MAX
};

enum EAuraGradeType
{
	AURA_GRADE_NONE,
	AURA_GRADE_ORDINARY,
	AURA_GRADE_SIMPLE,
	AURA_GRADE_NOBLE,
	AURA_GRADE_SPARKLING,
	AURA_GRADE_MAGNIFICENT,
	AURA_GRADE_RADIANT,
	AURA_GRADE_MAX_NUM,
};
enum EAuraRefineInfoType
{
	AURA_REFINE_INFO_STEP,
	AURA_REFINE_INFO_LEVEL_MIN,
	AURA_REFINE_INFO_LEVEL_MAX,
	AURA_REFINE_INFO_NEED_EXP,
	AURA_REFINE_INFO_MATERIAL_VNUM,
	AURA_REFINE_INFO_MATERIAL_COUNT,
	AURA_REFINE_INFO_NEED_GOLD,
	AURA_REFINE_INFO_EVOLVE_PCT,
	AURA_REFINE_INFO_MAX
};

enum ERefineInfoType
{
	AURA_REFINE_INFO_SLOT_CURRENT,
	AURA_REFINE_INFO_SLOT_NEXT,
	AURA_REFINE_INFO_SLOT_EVOLVED,
	AURA_REFINE_INFO_SLOT_MAX
};
#endif

#ifdef ENABLE_BATTLE_PASS_SYSTEM
enum EExtBattlePassInfo
{
	BATTLE_PASS_ITEM = 30346,
};

enum EExtBattlePassType
{
	BATTLEPASS_NORMAL,
	BATTLEPASS_PREMIUM,
	BATTLEPASS_EVENT,

	BATTLEPASS_TYPE_MAX,
};

enum EExtBattleMissionPassType
{
	MISSION_TYPE_NONE,

	KILL_MONSTER,
	KILL_PLAYER,

	DAMAGE_MONSTER,
	DAMAGE_PLAYER,

	BP_ITEM_USE,
	BP_ITEM_SELL,
	BP_ITEM_CRAFT,
	BP_ITEM_REFINE,
	BP_ITEM_DESTROY,
	BP_ITEM_COLLECT,

	FISH_FISHING,
	FISH_GRILL,
	FISH_CATCH,

	EXP_COLLECT,
	YANG_COLLECT,

	GUILD_PLAY_GUILDWAR,
	GUILD_SPENT_EXP,

	GAYA_CRAFT_GAYA,
	GAYA_BUY_ITEM_GAYA_COST,

	PET_ENCHANT,

	COMPLETE_DUNGEON,
	COMPLETE_MINIGAME,

	MISSION_TYPE_MAX,
};
#endif

enum DayMode : uint8_t
{
	DAY,
	NIGHT,
#ifdef ENABLE_WEATHER_INFO
	MORNING,
	EVENING,
	RAIN,
#endif
};

#ifdef ENABLE_WEATHER_INFO
enum DailyWeather : uint8_t
{
	MIDNIGHT	= 0,	// Mitternacht
	BEFORE_MID	= 23,	// Mitternacht

	SUNRISE		= 6,	// Sonnenaufgang
	NOON		= 9,	// Mittag
	SUNSET		= 18,	// Sonnenuntergang
	DARKNESS	= 20,	// Nacht
};
#endif

#ifdef ENABLE_EVENT_MANAGER
enum EEmpire
{
	ALL_EMPIRES,
	SHINSOO_EMPIRE,
	CHUNJO_EMPIRE,
	JINNO_EMPIRE
};
#endif

#ifdef ENABLE_BIOLOG_SYSTEM
enum EBiologBonuses
{
	MAX_BONUSES_LENGTH = 5,
};
#endif

#ifdef ENABLE_ATTR_6TH_7TH_EXTEND
enum EPvpAlignGrade
{
	PVP_LEVEL_CHIVALRIC,
	PVP_LEVEL_NOBLE,
	PVP_LEVEL_GOOD,
	PVP_LEVEL_FRIENDLY,
	PVP_LEVEL_NEUTRAL,
	PVP_LEVEL_AGGRESSIVE,
	PVP_LEVEL_FRAUDULENT,
	PVP_LEVEL_MALICIOUS,
	PVP_LEVEL_CRUEL
};
#endif

#ifdef ENABLE_CHECK_WINDOW_RENEWAL
enum ECheckWindow
{
	W_NONE				= (1 << 0),
	W_SAFEBOX			= (1 << 1),
	W_CUBE				= (1 << 2),
	W_EXCHANGE			= (1 << 3),
	W_MYSHOP			= (1 << 4),
	W_SHOP_OWNER		= (1 << 5),
	W_SKILLBOOK_COMB	= (1 << 6), // ENABLE_SKILLBOOK_COMBINATION
	W_ATTR_6TH_7TH		= (1 << 7), // ENABLE_ATTR_6TH_7TH
	W_ACCE				= (1 << 8), // ENABLE_ACCE_COSTUME_SYSTEM
	W_CHANGELOOK		= (1 << 9), // ENABLE_CHANGE_LOOK_SYSTEM
	W_AURA				= (1 << 10),// ENABLE_AURA_SYSTEM
#ifdef ENABLE_SWITCHBOT
	W_SWITCHBOT			= (1 << 11),
#endif
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
	W_GUILDBANK			= (1 << 12),
#endif
#ifdef ENABLE_SUMMER_EVENT_ROULETTE
	W_ROULETTE			= (1 << 13),
#endif
#ifdef ENABLE_MAILBOX
	W_MAILBOX			= (1 << 14),
#endif
	W_MAX_NUM			= (1 << 15),
};
#endif

#ifdef ENABLE_DELETE_FAILURE_TYPE
enum class EDeleteTypes : uint8_t
{
	DELETE_FAILURE_NORMAL,
	DELETE_FAILURE_HAVE_SEALED_ITEM,
	DELETE_FAILURE_PRIVATE_CODE_ERROR,
	DELETE_FAILURE_LIMITE_LEVEL_HIGHER,
	DELETE_FAILURE_LIMITE_LEVEL_LOWER,
	DELETE_FAILURE_REMAIN_TIME,
	DELETE_FAILURE_GUILD_MEMBER,
	DELETE_FAILURE_MARRIAGE,
	DELETE_FAILURE_LAST_CHAR_SAFEBOX,
	DELETE_FAILURE_ATTR67,
	DELETE_FAILURE_PREMIUM_PRIVATE_SHOP
};
#endif

#ifdef ENABLE_FLOWER_EVENT
enum EFlowerConfig
{
	FLOWER_COUNT_ITEM_DROP = 1,
	FLOWER_COUNT_ITEM_GIVE_EXCHANGE = 1,
	FLOWER_COUNT_FLOWER_EXCHANGE_CHEST = 10,
	FLOWER_VNUM_CHEST_FLOWER_1 = 83023,
	FLOWER_VNUM_CHEST_FLOWER_2 = 83024,
	FLOWER_VNUM_CHEST_FLOWER_3 = 83025,
	FLOWER_VNUM_CHEST_FLOWER_4 = 83026,
	FLOWER_VNUM_CHEST_FLOWER_5 = 83027,
	FLOWER_COUNT_ITEM_CHEST = 1,
	FLOWER_POWER_MAX_STAGE = 5,
};

enum EFlowerType
{
	PART_FLOWER_1,
	PART_FLOWER_2,
	PART_FLOWER_3,
	PART_FLOWER_4,
	PART_FLOWER_5,
	PART_FLOWER_6,
	STAGE_FLOWER,
	PART_FLOWER_MAX_NUM
};
#endif

#ifdef ENABLE_DUNGEON_INFO_SYSTEM
enum EDungeonInfoData
{
	MAX_REQUIRED_ITEMS = 3,
	MAX_BOSS_ITEM_SLOTS = 16,
	MAX_REFRESH_DELAY = 3,
};

enum EAction
{
	CLOSE,
	OPEN,
	WARP,
	RANK
};

enum ERank
{
	MAX_RANKING_LINES = 10,
	MAX_RANKING_COUNT = 10,
};

enum ERankTypes
{
	RANKING_TYPE_COMPLETED = 1,
	RANKING_TYPE_TIME = 2,
	RANKING_TYPE_DAMAGE = 3,

	MAX_RANKING_TYPE,
};
#endif

/*---| Dungeons |---*/
#ifdef ENABLE_BLUEDRAGON_RENEWAL
enum EBlueDragonRenewal
{
	BLUEDRAGON_BOSS = 2493,
	BLUEDRAGON_DEF_STONE = 8031,
	BLUEDRAGON_ATK_STONE = 8032,
	BLUEDRAGON_REGEN_TIME_STONE = 8033,
	BLUEDRAGON_REGEN_PECT_STONE = 8034
};
#endif

#ifdef ENABLE_SNOW_DUNGEON
enum ESnowDungeon
{
	SNOW_DUNGEON_STONE = 8058,
	SNOW_DUNGEON_SEMIBOSS = 6151,
	SNOW_DUNGEON_PILLAR = 20399
};
#endif

#ifdef ENABLE_DEFENSE_WAVE
enum EDefenseWaveDungeon
{
	DEFENSE_WAVE_MAST_VNUM = 20434,
	DEFENSE_WAVE_PORTAL = 3949,

	DEFENSE_WAVE_HYDRA1 = 3960,
	DEFENSE_WAVE_HYDRA2 = 3961,
	DEFENSE_WAVE_HYDRA3 = 3962,

	DEFENSE_WAVE_NEW_CONTINENT_X = 1686,
	DEFENSE_WAVE_NEW_CONTINENT_Y = 6112,
};
#endif

#ifdef ENABLE_SUNG_MAHI_TOWER
enum ESungMahiDungeon
{
	SUNG_MAHI_DAMANGE_MULTIPLIER = 5,
	SUNG_MAHI_DEFENCE_MULTIPLIER = 5,
	SUNG_MAHI_HP_MULTIPLIER = 250,
	SUNG_MAHI_MAX_LEVEL = 50,
};
#endif
/*---| END Dungeons |---*/

#ifdef ENABLE_MINI_GAME
#ifdef ENABLE_EVENT_BANNER_FLAG
enum EBannerType
{
	NONE_EVENT,

	FIND_M_EVENT,
	YUT_NORI_EVENT,

	EASTER_EVENT,
	HALLOWEEN_EVENT,
	RAMADAN_EVENT,
	XMAS_EVENT,

};
#endif

#ifdef ENABLE_MINI_GAME_OKEY_NORMAL
enum EMonsterOkeyCardEvent
{
	OKEY_CARD_NPC = 20417,

	RUMI_PLAY_YANG = 30000,
	RUMI_PLAY_ITEM = 79506,

	RUMI_REWARD_S = 50267,
	RUMI_REWARD_M = 50268,
	RUMI_REWARD_L = 50269,

	HAND_CARD_INDEX_MAX = 5,
	FIELD_CARD_INDEX_MAX = 3,
	FIELD_CARD_SLOT_MAX = 5,

	CARD_COLOR_MAX = 3,
	CARD_NUMBER_END = 8,
	DECK_COUNT_MAX = CARD_COLOR_MAX * CARD_NUMBER_END,

	LOW_TOTAL_SCORE = 300,
	MID_TOTAL_SCORE = 400,
};
#endif	// ENABLE_MINI_GAME_OKEY_NORMAL

#ifdef ENABLE_MONSTER_BACK
enum EMonsterBackEvent
{
	ATTENDANCE_NPC = 30131,

	ATTENDANCE_VNUM_BERAN = 6415,
	ATTENDANCE_VNUM_NEMERE = 6416,
	ATTENDANCE_VNUM_RAZADOR = 6417,
	ATTENDANCE_VNUM_JOTUN = 6418,
	ATTENDANCE_VNUM_RED_DRAGON = 6419,
#    ifdef ENABLE_10TH_EVENT
	ATTENDANCE_VNUM_SHADOW_WARRIOR = 6420,
#    endif
};
#endif	// ENABLE_MONSTER_BACK

#ifdef ENABLE_MINI_GAME_CATCH_KING
enum EMonsterCatchKingEvent
{
	CATCH_KING_NPC = 20506,
	CATCH_KING_DROP_ITEM = 79603,

	CATCH_KING_REWARD_S = 50930,
	CATCH_KING_REWARD_M = 50929,
	CATCH_KING_REWARD_L = 50928,

	CATCH_KING_PLAY_YANG = 30000,
	CATCH_KING_PLAY_ITEM = 79604,
};
#endif	// ENABLE_MINI_GAME_CATCH_KING

#ifdef ENABLE_FISH_EVENT
enum EFishEventInfo
{
	FISH_EVENT_SHAPE_NONE,
	FISH_EVENT_SHAPE_1,
	FISH_EVENT_SHAPE_2,
	FISH_EVENT_SHAPE_3,
	FISH_EVENT_SHAPE_4,
	FISH_EVENT_SHAPE_5,
	FISH_EVENT_SHAPE_6,
	FISH_EVENT_SHAPE_7,
	FISH_EVENT_SHAPE_MAX_NUM,
};

enum EFishEventData
{
	FISH_EVENT_SLOTS_NUM = 24,
	ITEM_FISH_EVENT_BOX = 25106,
	ITEM_FISH_EVENT_BOX_SPECIAL = 25107,
	ITEM_FISH_EVENT_REWARD_S = 83001,
	ITEM_FISH_EVENT_REWARD_M = 83002,
	ITEM_FISH_EVENT_REWARD_L = 83003,
};
#endif	// ENABLE_FISH_EVENT

#ifdef ENABLE_EASTER_EVENT
enum EEasterEventInfo
{
	EASTER_RABBIT_NPC = 30129,

	EASTER_EGG_VNUM_START = 50160,
	EASTER_EGG_VNUM_END = 50179,

	MAGIC_EGG_VNUM = 71150,
	MAGIC_EGG_TOTAL_UNPACK = 3,
	MAGIC_EGG_TIME_TO_WAIT = 30 * 60, // seconds
};
#endif	// ENABLE_EASTER_EVENT

#ifdef ENABLE_MINI_GAME_YUTNORI
enum EYutnoriEventInfo
{
	YUT_NORI_NPC = 20502,

	YUT_NORI_PLAY_YANG = 30000,
	YUT_NORI_DROP_ITEM = 79507,
	YUT_NORI_PLAY_ITEM = 79508,

	YUT_NORI_REWARD_GOLD = 50920,
	YUT_NORI_REWARD_SILVER = 50921,
	YUT_NORI_REWARD_BRONZE = 50922,

	YUT_NORI_YUTSEM1 = 0,
	YUT_NORI_YUTSEM2 = 1,
	YUT_NORI_YUTSEM3 = 2,
	YUT_NORI_YUTSEM4 = 3,
	YUT_NORI_YUTSEM5 = 4,
	YUT_NORI_YUTSEM6 = 5,
	YUT_NORI_YUTSEM_MAX = 6,

	YUTNORI_STATE_THROW = 0,
	YUTNORI_STATE_RE_THROW = 1,
	YUTNORI_STATE_MOVE = 2,
	YUTNORI_BEFORE_TURN_SELECT = 3,
	YUTNORI_AFTER_TURN_SELECT = 4,
	YUTNORI_STATE_END = 5,

	YUT_NORI_UNIT_MAX = 2,

	YUT_NORI_PLAYER = 0,
	YUT_NORI_COMPUTER = 1,
	YUT_NORI_PLAYER_MAX = 2,

	YUT_NORI_START_POS = 11,
	YUT_NORI_END_POS = 30,

	YUT_NORI_IN_DE_CREASE_SCORE = 10,
};
#endif	// ENABLE_MINI_GAME_YUTNORI

#ifdef ENABLE_MINI_GAME_FINDM
enum EFindMEventInfo
{
	FIND_M_NPC = 20507,

	FIND_M_PLAY_YANG = 30000,
	FIND_M_DROP_ITEM = 79510,
	FIND_M_PLAY_ITEM = 79511,

	FIND_M_REVEAL_TIME = 10, // Seconds

	FIND_M_REWARD_GOLD = 83033,
	FIND_M_REWARD_SILVER = 83034,
	FIND_M_REWARD_BRONZE = 83035,
	FIND_M_REWARD_VIP = 83040,

	FIND_M_BRONZE_START_COST = 50000, // Start cost after every upgrade multiply by 2
	FIND_M_SILVER_START_COST = 100000,
	FIND_M_GOLD_START_COST = 1000000,

	FIND_M_UPGRADE_CHANCE = 30, // 30%

	FIND_M_DEFAULT_HIT_COUNT = 2,
};
#endif	// ENABLE_MINI_GAME_FINDM

#ifdef ENABLE_MINI_GAME_BNW
enum EMiniGameBNW
{
	BNW_PLAY_YANG = 30000,
	BNW_DROP_ITEM = 79512,
	BNW_PLAY_ITEM = 79513,
	BNW_REWARD_VNUM = 79514,
	BNW_DONATION_PRICE = 15,

	BNW_CARD_MAX_NUM = 9,
};
#endif	// ENABLE_MINI_GAME_BNW

#ifdef ENABLE_WORLD_BOSS
enum WorldBossStates
{
	WORLD_BOSS_STATE_BOSS_KILLED,
	WORLD_BOSS_STATE_BOSS_SPAWNED,
	WORLD_BOSS_STATE_BREAK_TIME,
	WORLD_BOSS_STATE_WAIT_FOR_SPAWN,
};
#endif	// ENABLE_WORLD_BOSS
#endif	// ENABLE_MINI_GAME

#pragma pack(pop)

#endif
